trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      ls
      cd Terraform
      ls

- task: CmdLine@2
  inputs:
    script: 'ls'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'az-terraform'
    backendAzureRmResourceGroupName: 'Devops-RG'
    backendAzureRmStorageAccountName: 'devopsstorage0101'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: CmdLine@2
  inputs:
    script: |
      echo "______________"
      
      ls
      
      echo "______________"
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'az-terraform'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'az-terraform'
