trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: CmdLine@2
  inputs:
    script: 'ls'


- checkout: self
  path: Terraform

- task: CmdLine@2
  inputs:
    script: 'ls'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'az-terraform'
    backendAzureRmResourceGroupName: 'Devops-RG'
    backendAzureRmStorageAccountName: 'devopsstorage0101'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'az-terraform'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'az-terraform'
